# Generated by Django 5.2.14 on 2026-06-11 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=150, verbose_name='Tên đăng nhập')),
                ('action', models.CharField(choices=[('LOGIN', 'Đăng nhập'), ('LOGOUT', 'Đăng xuất'), ('CREATE', 'Thêm mới'), ('UPDATE', 'Cập nhật'), ('DELETE', 'Xóa'), ('UPLOAD_PDF', 'Upload PDF'), ('PREVIEW_PDF', 'Xem PDF'), ('DOWNLOAD_PDF', 'Tải PDF'), ('IMPORT_EXCEL', 'Import Excel'), ('EXPORT_EXCEL', 'Export Excel'), ('EXPORT_PDF', 'Export PDF'), ('SEARCH', 'Tìm kiếm'), ('VIEW_DASHBOARD', 'Xem dashboard'), ('VIEW_TREE', 'Xem cây lưu trữ'), ('API_CALL', 'Gọi API')], max_length=50, verbose_name='Hành động')),
                ('method', models.CharField(blank=True, default='', max_length=10, verbose_name='HTTP method')),
                ('path', models.CharField(max_length=500, verbose_name='Đường dẫn API')),
                ('status_code', models.PositiveIntegerField(blank=True, null=True, verbose_name='HTTP status')),
                ('object_type', models.CharField(blank=True, default='', max_length=150, verbose_name='Loại đối tượng')),
                ('object_id', models.CharField(blank=True, default='', max_length=100, verbose_name='ID đối tượng')),
                ('object_repr', models.CharField(blank=True, default='', max_length=500, verbose_name='Mô tả đối tượng')),
                ('request_data', models.JSONField(blank=True, null=True, verbose_name='Dữ liệu request')),
                ('response_data', models.JSONField(blank=True, null=True, verbose_name='Dữ liệu response')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Địa chỉ IP')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Nhật ký hệ thống',
                'verbose_name_plural': 'Nhật ký hệ thống',
                'db_table': 'audit_logs',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['created_at'], name='audit_logs_created_262184_idx'), models.Index(fields=['action'], name='audit_logs_action_31f574_idx'), models.Index(fields=['username'], name='audit_logs_usernam_eda0e7_idx'), models.Index(fields=['path'], name='audit_logs_path_efa6e3_idx'), models.Index(fields=['status_code'], name='audit_logs_status__45452f_idx')],
            },
        ),
    ]
