# Generated by Django 5.2.14 on 2026-06-11 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('files', '0001_initial'),
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OcrJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Đang chờ'), ('RUNNING', 'Đang xử lý'), ('COMPLETED', 'Hoàn thành'), ('FAILED', 'Thất bại')], default='PENDING', max_length=20, verbose_name='Trạng thái')),
                ('engine', models.CharField(blank=True, default='pymupdf+paddleocr', max_length=100, verbose_name='Công cụ OCR')),
                ('language', models.CharField(blank=True, default='vi', max_length=50, verbose_name='Ngôn ngữ OCR')),
                ('page_count', models.PositiveIntegerField(default=0, verbose_name='Số trang')),
                ('character_count', models.PositiveIntegerField(default=0, verbose_name='Số ký tự')),
                ('extracted_text', models.TextField(blank=True, default='', verbose_name='Text OCR')),
                ('normalized_text', models.TextField(blank=True, default='', verbose_name='Text OCR chuẩn hóa')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Lỗi')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Bắt đầu')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Kết thúc')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ocr_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Người chạy OCR')),
                ('digital_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_jobs', to='files.digitalfile', verbose_name='File số hóa')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocr_jobs', to='documents.document', verbose_name='Thành phần tài liệu')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocr_jobs', to='profiles.profile', verbose_name='Hồ sơ')),
            ],
            options={
                'verbose_name': 'OCR job',
                'verbose_name_plural': 'OCR jobs',
                'db_table': 'ocr_jobs',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status'], name='ocr_jobs_status_9c4e2c_idx'), models.Index(fields=['digital_file'], name='ocr_jobs_digital_2c722c_idx'), models.Index(fields=['profile'], name='ocr_jobs_profile_df827d_idx'), models.Index(fields=['document'], name='ocr_jobs_documen_0e26e7_idx'), models.Index(fields=['created_at'], name='ocr_jobs_created_d484ff_idx')],
            },
        ),
    ]
