# Generated by Django 5.2.14 on 2026-06-16 09:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('files', '0001_initial'),
        ('ocr', '0001_initial'),
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrjob',
            name='current_page',
            field=models.PositiveIntegerField(default=0, verbose_name='Trang hiện tại'),
        ),
        migrations.AddField(
            model_name='ocrjob',
            name='ocr_mode',
            field=models.CharField(choices=[('fast', 'Nhanh'), ('quality', 'Chất lượng cao')], default='fast', max_length=20, verbose_name='Chế độ OCR'),
        ),
        migrations.AddField(
            model_name='ocrjob',
            name='progress_percent',
            field=models.PositiveIntegerField(default=0, verbose_name='Tiến trình %'),
        ),
        migrations.AlterField(
            model_name='ocrjob',
            name='engine',
            field=models.CharField(blank=True, default='paddle', max_length=100, verbose_name='Công cụ OCR'),
        ),
        migrations.AddIndex(
            model_name='ocrjob',
            index=models.Index(fields=['ocr_mode'], name='ocr_jobs_ocr_mod_b53eca_idx'),
        ),
    ]
