# Generated by Django 5.2.14 on 2026-05-31 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fonds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Thời điểm cập nhật')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Đã xóa mềm')),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='Mã mục lục')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Tên mục lục')),
                ('year', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Năm')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('fond', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalogs', to='fonds.fond', verbose_name='Phông lưu trữ')),
            ],
            options={
                'verbose_name': 'Mục lục hồ sơ',
                'verbose_name_plural': 'Mục lục hồ sơ',
                'db_table': 'catalogs',
                'ordering': ['fond', 'year', 'code'],
                'unique_together': {('fond', 'code')},
            },
        ),
    ]
