# Generated by Django 5.2.14 on 2026-05-31 10:09

import apps.common.validators
import apps.files.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Thời điểm cập nhật')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Đã xóa mềm')),
                ('file', models.FileField(upload_to=apps.files.models.profile_pdf_upload_path, validators=[apps.common.validators.validate_file_size, apps.common.validators.validate_pdf_file], verbose_name='File PDF')),
                ('original_name', models.CharField(blank=True, max_length=500, verbose_name='Tên file gốc')),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Dung lượng file')),
                ('mime_type', models.CharField(blank=True, max_length=255, verbose_name='Loại file')),
                ('page_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Số trang PDF')),
                ('is_primary', models.BooleanField(db_index=True, default=False, verbose_name='File chính')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='digital_files', to='documents.document', verbose_name='Thành phần hồ sơ')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_files', to='profiles.profile', verbose_name='Hồ sơ')),
            ],
            options={
                'verbose_name': 'File số hóa',
                'verbose_name_plural': 'File số hóa',
                'db_table': 'digital_files',
                'ordering': ['profile', '-is_primary', 'id'],
            },
        ),
    ]
