# Generated by Step 21.13C1D-FIX2

import apps.common.validators
import apps.files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0002_alter_digitalfile_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="digitalfile",
            name="file",
            field=models.FileField(
                max_length=500,
                upload_to=apps.files.models.profile_pdf_upload_path,
                validators=[
                    apps.common.validators.validate_file_size,
                    apps.files.models.validate_digital_file_type,
                ],
                verbose_name="File số hóa",
            ),
        ),
    ]
