# Generated by Django 5.2.14 on 2026-05-31 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Thời điểm cập nhật')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Đã xóa mềm')),
                ('code', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Mã phông')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Tên phông')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Phông lưu trữ',
                'verbose_name_plural': 'Phông lưu trữ',
                'db_table': 'fonds',
                'ordering': ['code'],
            },
        ),
    ]
