# Generated by Django 5.2.14 on 2026-06-19 03:10

import apps.common.validators
import apps.files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalfile',
            name='file',
            field=models.FileField(upload_to=apps.files.models.profile_pdf_upload_path, validators=[apps.common.validators.validate_file_size, apps.files.models.validate_digital_file_type], verbose_name='File số hóa'),
        ),
    ]
