# Generated by Django 5.2.14 on 2026-05-31 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Thời điểm cập nhật')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Đã xóa mềm')),
                ('document_code', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Số/ký hiệu văn bản')),
                ('title', models.CharField(db_index=True, max_length=1000, verbose_name='Tên tài liệu')),
                ('document_date', models.DateField(blank=True, null=True, verbose_name='Ngày văn bản')),
                ('author', models.CharField(blank=True, db_index=True, max_length=500, verbose_name='Tác giả/cơ quan ban hành')),
                ('page_start', models.PositiveIntegerField(blank=True, null=True, verbose_name='Từ trang')),
                ('page_end', models.PositiveIntegerField(blank=True, null=True, verbose_name='Đến trang')),
                ('summary', models.TextField(blank=True, verbose_name='Trích yếu/nội dung')),
                ('search_text', models.TextField(blank=True, db_index=True, verbose_name='Text tìm kiếm chuẩn hóa')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='profiles.profile', verbose_name='Hồ sơ')),
            ],
            options={
                'verbose_name': 'Thành phần hồ sơ',
                'verbose_name_plural': 'Thành phần hồ sơ',
                'db_table': 'documents',
                'ordering': ['profile', 'document_date', 'id'],
                'indexes': [models.Index(fields=['document_code'], name='documents_documen_d6b9b9_idx'), models.Index(fields=['title'], name='documents_title_3f6c9c_idx'), models.Index(fields=['author'], name='documents_author_65ccec_idx'), models.Index(fields=['search_text'], name='documents_search__86e1e5_idx')],
            },
        ),
    ]
