# Generated by Django 5.2.14 on 2026-06-19 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('profiles', '0002_profile_cataloging_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['profile', 'order_in_profile', 'document_date', 'document_code'], 'verbose_name': 'Bản ghi', 'verbose_name_plural': 'Bản ghi'},
        ),
        migrations.AddField(
            model_name='document',
            name='attachment_note',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Tệp/tập tin đính kèm văn bản'),
        ),
        migrations.AddField(
            model_name='document',
            name='copy_type',
            field=models.CharField(blank=True, max_length=255, verbose_name='Loại bản'),
        ),
        migrations.AddField(
            model_name='document',
            name='digital_signature',
            field=models.CharField(blank=True, max_length=500, verbose_name='Chữ ký số'),
        ),
        migrations.AddField(
            model_name='document',
            name='document_identifier',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Mã định danh tài liệu'),
        ),
        migrations.AddField(
            model_name='document',
            name='document_number',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Số văn bản'),
        ),
        migrations.AddField(
            model_name='document',
            name='document_symbol',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Ký hiệu văn bản'),
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Tên thể loại văn bản'),
        ),
        migrations.AddField(
            model_name='document',
            name='language',
            field=models.CharField(blank=True, default='Tiếng Việt', max_length=100, verbose_name='Ngôn ngữ'),
        ),
        migrations.AddField(
            model_name='document',
            name='note',
            field=models.TextField(blank=True, verbose_name='Ghi chú'),
        ),
        migrations.AddField(
            model_name='document',
            name='order_in_profile',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Số thứ tự văn bản trong hồ sơ'),
        ),
        migrations.AddField(
            model_name='document',
            name='page_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Số lượng trang'),
        ),
        migrations.AddField(
            model_name='document',
            name='page_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Trang số'),
        ),
        migrations.AddField(
            model_name='document',
            name='security_level',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Độ mật'),
        ),
        migrations.AddField(
            model_name='document',
            name='signer',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Người ký'),
        ),
        migrations.AlterField(
            model_name='document',
            name='author',
            field=models.CharField(blank=True, db_index=True, max_length=500, verbose_name='Tác giả/Cơ quan ban hành'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_code',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Số/ký hiệu văn bản'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Ngày/tháng/năm văn bản'),
        ),
        migrations.AlterField(
            model_name='document',
            name='page_end',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Trang kết thúc'),
        ),
        migrations.AlterField(
            model_name='document',
            name='page_start',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Trang bắt đầu'),
        ),
        migrations.AlterField(
            model_name='document',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='profiles.profile', verbose_name='Hồ sơ'),
        ),
        migrations.AlterField(
            model_name='document',
            name='summary',
            field=models.TextField(blank=True, verbose_name='Trích yếu nội dung'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(db_index=True, max_length=1000, verbose_name='Tiêu đề/Tên gọi văn bản'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_identifier'], name='documents_documen_ce631e_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_number'], name='documents_documen_19bab8_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_symbol'], name='documents_documen_965036_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_type'], name='documents_documen_fc21d0_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_date'], name='documents_documen_718437_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['signer'], name='documents_signer_d85eb6_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['security_level'], name='documents_securit_d90841_idx'),
        ),
    ]
