"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv
import os
from config.env_contract import (
    get_app_env,
    get_env_bool,
    get_env_csv,
    get_env_value,
    resolve_database_config,
    resolve_storage_root,
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_env_value(
    "SECRET_KEY",
    aliases=("DJANGO_SECRET_KEY",),
    default="fallback-secret-key",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = get_env_bool("DEBUG", aliases=("DJANGO_DEBUG",), default=False)

ALLOWED_HOSTS = get_env_csv("ALLOWED_HOSTS", aliases=("DJANGO_ALLOWED_HOSTS",), default="localhost,127.0.0.1")
APP_ENV = get_app_env()
CSRF_TRUSTED_ORIGINS = get_env_csv("CSRF_TRUSTED_ORIGINS", default="")


# Application definition

INSTALLED_APPS = [
    # Django default apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third-party apps
    "rest_framework",
    "corsheaders",
    "django_filters",
    "drf_spectacular",
    "rest_framework_simplejwt.token_blacklist",

    # Local apps
    "apps.accounts",
    "apps.permissions",
    "apps.fonds",
    "apps.catalogs",
    "apps.storage",
    "apps.profiles",
    "apps.documents",
    "apps.files",
    "apps.search",
    "apps.ocr",
    "apps.imports",
    "apps.exports",
    "apps.audit",
    "apps.reports",
    "apps.common",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "apps.audit.middleware.AuditLogMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "config.middleware.JsonUtf8CharsetMiddleware",
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DB_ENGINE, _DATABASE_DEFAULT = resolve_database_config(BASE_DIR, app_env=APP_ENV)
DATABASES = {"default": _DATABASE_DEFAULT}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "EXCEPTION_HANDLER": "apps.common.exceptions.custom_exception_handler",
    "DEFAULT_PAGINATION_CLASS": "apps.common.pagination.StandardResultsSetPagination",
    "PAGE_SIZE": 20,
}

SPECTACULAR_SETTINGS = {
    "TITLE": os.getenv("APP_NAME", "Archive Management API"),
    "DESCRIPTION": "API quản lý kho lưu trữ hồ sơ, tài liệu số hóa",
    "VERSION": os.getenv("APP_VERSION", "1.0.0"),
    "SERVE_INCLUDE_SCHEMA": False,
}

CORS_ALLOWED_ORIGINS = get_env_csv(
    "CORS_ALLOWED_ORIGINS",
    default="http://localhost:3000,http://127.0.0.1:3000",
)

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(
        minutes=int(os.getenv("JWT_ACCESS_TOKEN_MINUTES", 60))
    ),
    "REFRESH_TOKEN_LIFETIME": timedelta(
        days=int(os.getenv("JWT_REFRESH_TOKEN_DAYS", 7))
    ),
    "AUTH_HEADER_TYPES": ("Bearer",),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
}


MAX_UPLOAD_SIZE_MB = int(os.getenv("MAX_UPLOAD_SIZE_MB", 100))

DEFAULT_CHARSET = "utf-8"

# WEB-24 LARGE STORAGE CONFIG
# Mặc định giữ nguyên thư mục media hiện tại để không làm mất file cũ.
# Khi cài máy thật có ổ 500GB/TB, chỉ cần set biến môi trường ARCHIVE_STORAGE_ROOT.
def _archive_env_int(name: str, default: int) -> int:
    try:
        return int(os.environ.get(name, default))
    except (TypeError, ValueError):
        return default


ARCHIVE_STORAGE_ROOT = resolve_storage_root(BASE_DIR)
MEDIA_ROOT = ARCHIVE_STORAGE_ROOT
MEDIA_URL = get_env_value("MEDIA_URL", default="/media/")

# Cho phép upload file lớn hơn mặc định. Với file rất lớn, Django vẫn ghi ra file tạm,
# không giữ toàn bộ trong RAM.
FILE_UPLOAD_MAX_MEMORY_SIZE = _archive_env_int(
    "FILE_UPLOAD_MAX_MEMORY_SIZE",
    100 * 1024 * 1024,
)
DATA_UPLOAD_MAX_MEMORY_SIZE = _archive_env_int(
    "DATA_UPLOAD_MAX_MEMORY_SIZE",
    100 * 1024 * 1024,
)

# Mốc cảnh báo dung lượng.
ARCHIVE_STORAGE_TARGET_BYTES = _archive_env_int(
    "ARCHIVE_STORAGE_TARGET_BYTES",
    500 * 1024 * 1024 * 1024,
)
ARCHIVE_STORAGE_LOW_FREE_BYTES = _archive_env_int(
    "ARCHIVE_STORAGE_LOW_FREE_BYTES",
    20 * 1024 * 1024 * 1024,
)
ARCHIVE_STORAGE_WARNING_PERCENT = _archive_env_int(
    "ARCHIVE_STORAGE_WARNING_PERCENT",
    10,
)
