# Generated by Django 5.2.14 on 2026-05-31 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Thời điểm cập nhật')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Đã xóa mềm')),
                ('profile_code', models.CharField(db_index=True, max_length=255, verbose_name='Số/ký hiệu hồ sơ')),
                ('title', models.CharField(db_index=True, max_length=1000, verbose_name='Tiêu đề hồ sơ')),
                ('description', models.TextField(blank=True, verbose_name='Nội dung/mô tả hồ sơ')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc')),
                ('year', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Năm hồ sơ')),
                ('total_pages', models.PositiveIntegerField(blank=True, null=True, verbose_name='Số tờ/trang')),
                ('retention_period', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Thời hạn bảo quản')),
                ('language', models.CharField(blank=True, default='Tiếng Việt', max_length=100, verbose_name='Ngôn ngữ')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('search_text', models.TextField(blank=True, db_index=True, verbose_name='Text tìm kiếm chuẩn hóa')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='catalogs.catalog', verbose_name='Mục lục')),
                ('storage_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='storage.storagefile', verbose_name='Tệp trong hộp')),
            ],
            options={
                'verbose_name': 'Hồ sơ',
                'verbose_name_plural': 'Hồ sơ',
                'db_table': 'profiles',
                'ordering': ['catalog', 'profile_code'],
                'indexes': [models.Index(fields=['profile_code'], name='profiles_profile_1c8da9_idx'), models.Index(fields=['title'], name='profiles_title_3ecf83_idx'), models.Index(fields=['year'], name='profiles_year_320228_idx'), models.Index(fields=['search_text'], name='profiles_search__0ed30d_idx')],
            },
        ),
    ]
