# Generated by Django 5.2.14 on 2026-06-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0001_initial'),
        ('profiles', '0001_initial'),
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='file_notation',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Số và ký hiệu hồ sơ'),
        ),
        migrations.AddField(
            model_name='profile',
            name='historical_archive_code',
            field=models.CharField(blank=True, max_length=255, verbose_name='Mã cơ quan lưu trữ lịch sử'),
        ),
        migrations.AddField(
            model_name='profile',
            name='keywords',
            field=models.TextField(blank=True, verbose_name='Từ khóa'),
        ),
        migrations.AddField(
            model_name='profile',
            name='physical_condition',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tình trạng vật lý'),
        ),
        migrations.AddField(
            model_name='profile',
            name='preservation_unit_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Đơn vị bảo quản số'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_group_name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Tên nhóm hồ sơ'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_type',
            field=models.CharField(blank=True, default='Hồ sơ', max_length=100, verbose_name='Loại hồ sơ'),
        ),
        migrations.AddField(
            model_name='profile',
            name='storage_position_text',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Cấp số hoặc kho/giá/cặp số'),
        ),
        migrations.AddField(
            model_name='profile',
            name='topic',
            field=models.CharField(blank=True, max_length=500, verbose_name='Chuyên đề'),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_documents',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tổng số tài liệu trong hồ sơ'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Thời gian kết thúc'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='note',
            field=models.TextField(blank=True, verbose_name='Chú thích/Ghi chú'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_code',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Mã hồ sơ'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Thời gian bắt đầu'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='total_pages',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tổng số trang trong hồ sơ'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['file_notation'], name='profiles_file_no_33e4e6_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['retention_period'], name='profiles_retenti_b2ef50_idx'),
        ),
    ]
