# Generated by Django 5.2.14 on 2026-05-31 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
        ('fonds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Thời điểm cập nhật')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Đã xóa mềm')),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='Mã vị trí')),
                ('name', models.CharField(max_length=255, verbose_name='Tên vị trí')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Vị trí lưu trữ',
                'verbose_name_plural': 'Vị trí lưu trữ',
                'db_table': 'storage_locations',
                'ordering': ['warehouse', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Thời điểm cập nhật')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Đã xóa mềm')),
                ('code', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Mã kho')),
                ('name', models.CharField(max_length=255, verbose_name='Tên kho')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Địa chỉ')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Kho lưu trữ',
                'verbose_name_plural': 'Kho lưu trữ',
                'db_table': 'warehouses',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='StorageBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Thời điểm cập nhật')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Đã xóa mềm')),
                ('box_number', models.CharField(db_index=True, max_length=100, verbose_name='Hộp số')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Tiêu đề hộp')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('catalog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='boxes', to='catalogs.catalog', verbose_name='Mục lục')),
                ('fond', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boxes', to='fonds.fond', verbose_name='Phông lưu trữ')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boxes', to='storage.storagelocation', verbose_name='Vị trí lưu trữ')),
            ],
            options={
                'verbose_name': 'Hộp lưu trữ',
                'verbose_name_plural': 'Hộp lưu trữ',
                'db_table': 'storage_boxes',
                'ordering': ['fond', 'box_number'],
                'unique_together': {('fond', 'box_number')},
            },
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='storage.warehouse', verbose_name='Kho'),
        ),
        migrations.CreateModel(
            name='StorageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Thời điểm cập nhật')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Đã xóa mềm')),
                ('file_number', models.CharField(db_index=True, max_length=100, verbose_name='Tệp số')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Tiêu đề tệp')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='storage_files', to='storage.storagebox', verbose_name='Hộp')),
            ],
            options={
                'verbose_name': 'Tệp trong hộp',
                'verbose_name_plural': 'Tệp trong hộp',
                'db_table': 'storage_files',
                'ordering': ['box', 'file_number'],
                'unique_together': {('box', 'file_number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='storagelocation',
            unique_together={('warehouse', 'code')},
        ),
    ]
